import "./globals.css";
import type { Metadata } from "next";
import { Inter, Bebas_Neue,Chakra_Petch } from "next/font/google";

const inter = Chakra_Petch({
  subsets: ["vietnamese"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
